### ISSUE TITLE
why it doesn't working?

### ISSUE THREAD

**Issue by ruvaleev** [jpweinerdev/timerangewheelslider.js#3]
I trying install this plugin to my Ruby on Rails project, but when the page is uploading, there is error messages in console:
TypeError: $(...).timerangewheel is not a function
TypeError: $(...).animate is not a function

And I can't find it in your code. What am I doing wrong? And how can I get that functions?

**Comment by jpweinerdev** [comment]
Please check if you have all dependencies linked:
jQuery
d3.js
Initialize the plugin within document-ready-function:
$(document).ready(function(){
/* your script here */
});
